ProjectManager.Web/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProjectManager.Core.Contracts;
using ProjectManager.Core.Entities;
using ProjectManager.Web.Models;
using ProjectManager.Web.Models.ViewModel;
using ProjectManager.Web.Models.ViewModel.Employees;
using Task = ProjectManager.Core.Entities.Task;

namespace ProjectManager.Web.Controllers
{
    public class EmployeesController : Controller
    {
        #region fields

        IUnitOfWork _unitOfWork;
        private UserManager<ApplicationUser> _userManager;
        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        #endregion

        #region Constructor

        public EmployeesController(IUnitOfWork unitOfWork, UserManager<ApplicationUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
        }

        #endregion

        #region List

        public IActionResult List()
        {
            EmployeesListViewModel model = new EmployeesListViewModel();
            model.LoadData(_unitOfWork);

            return View(model);
        }

        [HttpPost]
        public IActionResult List(EmployeesListViewModel model)
        {
            if (model.LastnameFilter != null)
            {
                model.LoadListData(_unitOfWork, 1);
            }
            else if (model.FirstnameFilter != null)
            {
                model.LoadListData(_unitOfWork, 2);
            }
            else if (model.JobFilter != null)
            {
                model.LoadListData(_unitOfWork, 3);
            }
            else if (model.DepartmentFilter != null)
            {
                model.LoadListData(_unitOfWork, 4);
            }
            else
            {
                return NotFound();
            }

            return View(model);
        }

        #endregion

        #region Profil

        public async Task<ActionResult> Profil(int employeeId)
        {
            EmployeesProfilViewModel model = new EmployeesProfilViewModel();

            var user = await GetCurrentUserAsync();

            var UserId = (int)user?.EmployeeId;

            if (employeeId == 0)
            {
                model.IsUserMe = true;
                model.LoadProfilData(_unitOfWork, UserId);
            }
            else
            {
                model.IsUserMe = CheckIfUserIsMe(UserId, employeeId);
                model.LoadProfilData(_unitOfWork, employeeId);
            }

            if (model.Employee == null)
                return NotFound();

            return View(model);
        }

        public IActionResult EditProfil(int employeeId)
        {
            EmployeesEditProfilViewModel model = new EmployeesEditProfilViewModel();
            model.LoadEditProfilData(_unitOfWork, employeeId);
            if (model.Employee == null)
                return NotFound();

            return View(model);
        }

        [HttpPost]
        public IActionResult EditProfil(EmployeesEditProfilViewModel model)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Employees.Update(model.Employee);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Profil), new
                {
                    employeeId = model.Employee.Id
                });
            }
            else
            {
                model.Error = true;
                model.LoadEditProfilData(_unitOfWork, model.Employee.Id);
                return View(model);
            }
        }
        #endregion

        #region Dashboard
        public async Task<ActionResult> Feed(int employeeId, string buttonClicked, bool priority, string error)
        {
            EmployeesFeedViewModel model = new EmployeesFeedViewModel();
            var user = await GetCurrentUserAsync();

            var UserId = (int)user?.EmployeeId;

            if (employeeId == 0)
            {
                model.IsUserMe = true;
                model.LoadDashboardData(UserId, _unitOfWork);
            }
            else if (buttonClicked == null)
            {
                model.IsUserMe = CheckIfUserIsMe(UserId, employeeId);
                model.LoadDashboardData(employeeId, _unitOfWork);
            }
            else
            {
                model.IsUserMe = CheckIfUserIsMe(UserId, employeeId);
                model.Employee = _unitOfWork.Employees.GetById(employeeId);
                model.ButtonClicked = buttonClicked;
                GetFilteredList(model, priority);
            }

            if (error != null)
                HandleOccuredError(model, error);

            if (model == null)
                return NotFound();

            return View(model);
        }

        [HttpPost]
        public IActionResult Feed(EmployeesFeedViewModel model)
        {
            if (model.ProjectFilter != null)
            {
                model.LoadProjectDashboardData(model.Employee.Id, _unitOfWork, "All", IsPriorityButtonClicked(model.PriorityFilter));
            }
            else if (model.Assigned != null)
            {
                model.LoadDashboardData(model.Employee.Id, _unitOfWork);
            }
            else if (model.GeneralFilter != null)
            {
                model.LoadProjectDashboardData(model.Employee.Id, _unitOfWork, "General", IsPriorityButtonClicked(model.PriorityFilter));
            }
            else if (model.PriorityFilter != null)
            {
                GetFilteredList(model, IsPriorityButtonClicked(model.PriorityFilter));
            }
            else if (model.Search != null)
            {
                GetFilteredList(model, IsPriorityButtonClicked(model.PriorityFilter));
            }
            else
            {
                return NotFound();
            }

            return View(model);
        }

        public IActionResult DeleteAppointment(int employeeId, int appointmentId, string buttonClicked, string priorityButton)
        {
            DashboardDisplay dashboardDisplay = _unitOfWork.DashboardDisplays.GetByEmployeeIdAndAppointmentId(employeeId, appointmentId);

            this.DeleteDashBoardTask(dashboardDisplay);
            _unitOfWork.Save();

            return RedirectToAction(nameof(Feed), new
            {
                employeeId = employeeId,
                buttonClicked = buttonClicked,
                priority = IsPriorityButtonClicked(priorityButton)
            });
        }

        public IActionResult AddTask(int employeeId, int taskId, string buttonClicked, string priorityButton)
        {
            return RedirectToAction(nameof(Feed), new
            {
                employeeId = employeeId,
                buttonClicked = buttonClicked,
                priority = IsPriorityButtonClicked(priorityButton),
                error = CheckIfEmployeeTaskExists(employeeId, taskId)
            });
        }

        #region Feed : Methods

        public void GetFilteredList(EmployeesFeedViewModel model, bool priority)
        {
            if (model.ButtonClicked == "Project")
            {
                model.LoadProjectDashboardData(model.Employee.Id, _unitOfWork, "All", priority);
            }
            else if (model.ButtonClicked == "Assigned")
            {
                model.LoadDashboardData(model.Employee.Id, _unitOfWork);
            }
            else if (model.ButtonClicked == "General")
            {
                model.LoadProjectDashboardData(model.Employee.Id, _unitOfWork, "General", priority);
            }
        }

        public string CheckIfEmployeeTaskExists(int employeeId, int taskId)
        {
            string errorMessage = null;
            EmployeeTask employeeTask = new EmployeeTask();
            employeeTask = _unitOfWork.EmployeeTasks.GetByEmployeeIdAndTaskId(employeeId, taskId);

            if (employeeTask == null)
            {
                employeeTask = GenerateEmployeetask(employeeId, taskId);

                if (CreateEmployeeTask(employeeTask))
                {
                    if (!SetUpForDashboardDisplay(employeeTask))
                    {
                        errorMessage = "Error during the creation of the DashboardDisplay!";
                    }
                }
                else
                {
                    errorMessage = "Error during the creation of the EmployeeTask!";
                }
            }
            else
            {
                employeeTask.Picked = true;

                if (UpdateEmployeeTask(employeeTask))
                {
                    if (!SetUpForDashboardDisplay(employeeTask))
                    {
                        errorMessage = "Error during the creation of the DashboardDisplay!";
                    }
                }
                else
                {
                    errorMessage = "Error during the update of the EmployeeTask!";
                }
            }

            return errorMessage;
        }

        private bool IsPriorityButtonClicked(string priority)
        {
            return priority != null;
        }

        private void HandleOccuredError(EmployeesFeedViewModel model, string error)
        {
            model.Error = true;
            model.Errormessage = error;
        }
        #endregion

        #endregion

        #region FinishOrPass

        public IActionResult FinishOrPass(int employeeId, int taskId, string buttonClicked, bool priority)
        {
            EmployeesFinishOrPassViewModel model = new EmployeesFinishOrPassViewModel();
            model.LoadData(_unitOfWork, employeeId, taskId);
            model.ButtonClicked = buttonClicked;
            model.Priority = priority;
            return View(model);
        }

        [HttpPost]

ProjectManager.Web/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProjectManager.Core.Contracts;
using ProjectManager.Core.Entities;
using ProjectManager.Web.Models;
using ProjectManager.Web.Models.ViewModel;

namespace ProjectManager.Web.Controllers
{
    public class ProjectsController : Controller
    {
        IUnitOfWork _unitOfWork;

        public ProjectsController(IUnitOfWork unitofwork)
        {
            _unitOfWork = unitofwork;
        }

        /// <summary>
        /// Lukas Schütz Created
        /// </summary>
        /// <returns></returns>
        public IActionResult List()
        {
            ProjectsListViewModel model = new ProjectsListViewModel();
            model.LoadData(_unitOfWork);
            return View(model);
        }

        /// <summary>
        /// Lukas Schütz Created
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult List(ProjectsListViewModel model)
        {
            model.Projects = _unitOfWork.Projects.GetProjectByName(model.FilterProjectName);
            return View(model);
        }

        /// <summary>
        /// Lukas Schütz Created
        /// </summary>
        /// <param name="projectId"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int projectId)
        {
            ProjectsEditViewModel model = new ProjectsEditViewModel();
            model.LoadData(_unitOfWork, projectId);

            return View(model);
        }

        /// <summary>
        /// Lukas Schütz Created
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(ProjectsEditViewModel model)
        {
            Employee employee = _unitOfWork.Employees.GetById(model.EditEmployee.Id);

            _unitOfWork.EmployeeProjects.SetAllProjectManagersToFalse(model.Project.Id);

            EmployeeProject employeeProject = _unitOfWork.EmployeeProjects.GetByEmployeeIdAndProjectId(model.Project.Id, model.EditEmployee.Id);

            employeeProject.Projectmanager = true;

            if (ModelState.IsValid)
            {
                try
                {
                    _unitOfWork.Projects.Update(model.Project);
                    _unitOfWork.EmployeeProjects.Update(employeeProject);
                    _unitOfWork.Save();
                    return RedirectToAction(nameof(List));
                }
                catch (ValidationException validationException)
                {
                    ValidationResult valResult = validationException.ValidationResult;
                    ModelState.AddModelError(nameof(model) + "." + valResult.MemberNames.First(), valResult.ErrorMessage);
                }
                
            }

            return View(model);
        }

        /// <summary>
        /// Lukas Schütz Created
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ProjectsCreateViewModel model = new ProjectsCreateViewModel();
            model.LoadData(_unitOfWork);
            return View(model);
        }

        /// <summary>
        /// Lukas Schütz Created
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(ProjectsCreateViewModel model)
        {
            

            if (ModelState.IsValid)
            {
                try
                {
                    model.EmployeeProject.Projectmanager = true;
                    _unitOfWork.Projects.Add(model.EmployeeProject.Project);
                    _unitOfWork.EmployeeProjects.Add(model.EmployeeProject);
                    _unitOfWork.Save();
                    return RedirectToAction("Create", "EmployeeProjects", new { projectId = model.EmployeeProject.ProjectId });
                }
                catch (ValidationException validationException)
                {
                    ValidationResult valResult = validationException.ValidationResult;
                    ModelState.AddModelError(nameof(model) + "." + valResult.MemberNames.First(), valResult.ErrorMessage);
                }
            }

            return View(model);
        }

        /// <summary>
        /// Lukas Schütz Created
        /// </summary>
        /// <param name="projectId"></param>
        /// <returns></returns>
        public IActionResult Details(int projectId)
        {
            ProjectsDetailsViewModel model = new ProjectsDetailsViewModel();
            model.LoadData(_unitOfWork, projectId);
            return View(model);   
        }

        /// <summary>
        /// Lukas Schütz Created
        /// </summary>
        /// <param name="projectId"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int projectId)
        {
            Project model = _unitOfWork.Projects.GetById(projectId);

            if(model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        /// <summary>
        /// Lukas Schütz Created
        /// </summary>
        /// <param name="projectId"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult DeleteConfirm(int projectId)
        {
            Project model = _unitOfWork.Projects.GetById(projectId);

            if(model == null)
            {
                return NotFound();
            }
            _unitOfWork.Projects.Delete(model);
            _unitOfWork.Save();
            return RedirectToAction(nameof(List));
        }

    }
}

ProjectManager.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectManager.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="https://unpkg.com/envoy.css@1.6.15/css/envoy.min.css">
    </environment>
    <style>
    </style>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <div>
                            <a asp-area="" asp-controller="Employees" asp-action="Feed" asp-route-employeeId="0" class="navbar-brand">Project Manager</a>
                        </div>
                    }

                </div>
                <div class="navbar-collapse collapse">
                    @if (User.Identity.IsAuthenticated && !User.IsInRole("Admin"))
                    {
                        <ul class="nav navbar-nav">
                            <li><a asp-area="" asp-controller="Tasks" asp-action="List">Tasks</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Employees<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a asp-area="" asp-controller="Employees" asp-action="Feed" asp-route-employeeId="0">my Dashboard</a></li>
                                    <li><a asp-area="" asp-controller="Employees" asp-action="Profil" asp-route-employeeId="0">my Profil</a></li>
                                    <li><a asp-area="" asp-controller="Employees" asp-action="List">Employeelist</a></li>
                                </ul>
                            </li>
                            <li title="Click here to see the list of all departments"><a asp-area="" asp-controller="Departments" asp-action="List">Departments</a></li>
                            <li><a asp-area="" asp-controller="Projects" asp-action="List">Projects</a></li>
                        </ul>
                    }
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <ul class="nav navbar-nav">
                            <li><a asp-area="" asp-controller="Tasks" asp-action="List">Tasks</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Employees<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a asp-area="" asp-controller="Employees" asp-action="Feed" asp-route-employeeId="0">my Dashboard</a></li>
                                    <li><a asp-area="" asp-controller="Employees" asp-action="Profil" asp-route-employeeId="0">my Profil</a></li>
                                    <li><a asp-area="" asp-controller="Employees" asp-action="List">Employeelist</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Departments<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li title="Click here to see the list of all departments"><a asp-area="" asp-controller="Departments" asp-action="List">List of departments</a></li>
                                    <li><a asp-area="" asp-controller="Departments" asp-action="Create">Create department</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Qualifications<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a asp-area="" asp-controller="Qualifications" asp-action="List">Overview</a></li>
                                    <li><a asp-area="" asp-controller="Qualifications" asp-action="Create">Create a Qualification</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Projects<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a asp-area="" asp-controller="Projects" asp-action="List">Overview</a></li>
                                    <li><a asp-area="" asp-controller="Projects" asp-action="Create">Create a Project</a></li>
                                </ul>
                            </li>
                            <li><a asp-area="Identity" asp-page="/Account/Register">Register</a></li>
                        </ul>
                    }
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </div>

    @*<partial name="_CookieConsentPartial" />*@

    <div class="container body-content">
        @RenderBody()
        <footer>
            <p></p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>