ProjectManager.Web/Controllers/EmployeeTasksController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ProjectManager.Core.Contracts;
using ProjectManager.Core.Entities;
using ProjectManager.Web.Models.ViewModel;

namespace ProjectManager.Web.Controllers
{
    public class EmployeeTasksController : Controller
    {
        IUnitOfWork _unitOfWork;

        public EmployeeTasksController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        /// <summary>
        /// Manuel Mairinger Created
        /// </summary>
        /// <param name="taskId"></param>
        /// <param name="projectId"></param>
        /// <param name="emptaskId"></param>
        /// <returns></returns>

        public IActionResult Create(int taskId, int projectId, int emptaskId)
        {
            EmployeeTasksCreateViewModel model = new EmployeeTasksCreateViewModel();
            model.LoadData(_unitOfWork, taskId, projectId,emptaskId);
            model.EmployeeTask.Employee = _unitOfWork.Employees.GetById(model.EmployeeTask.EmployeeId);
            return View(model);
        }


        /// <summary>
        /// Manuel Mairinger Created
        /// </summary>
        /// <param name="taskId"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Create( int taskId)
        {

            EmployeeTask model = new EmployeeTask {  TaskId = taskId };

            if (ModelState.IsValid)
            {
                try
                {
                    _unitOfWork.EmployeeTasks.Add(model);
                    _unitOfWork.Save();
                    return RedirectToAction("Create", new { taskId = model.TaskId });
                }
                catch (ValidationException validationException)
                {
                    ValidationResult valResult = validationException.ValidationResult;
                    ModelState.AddModelError(nameof(model) + "." + valResult.MemberNames.First(), valResult.ErrorMessage);
                }
            }

            return View(model);
        }


        /// <summary>
        /// Manuel Mairinger Created
        /// </summary>
        /// <param name="empTaskId"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Delete(int empTaskId)
        {
            EmployeeTask model = _unitOfWork.EmployeeTasks.GetById(empTaskId);

            if (model == null)
            {
                return NotFound();
            }
            _unitOfWork.EmployeeTasks.Delete(model);
            _unitOfWork.Save();
            return RedirectToAction(nameof(Create), new { taskId = model.TaskId});
        }

    }
}

ProjectManager.Web/Views/EmployeeTasks/Create.cshtml
@model ProjectManager.Web.Models.ViewModel.EmployeeTasksCreateViewModel

@{
    ViewData["Title"] = "Create";
}

@*<h2>Mitarbeiter zum Task "@Model.Task.TaskName" hinzufügen</h2>*@

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        </form>
    </div>
</div>
<h2>Task-Mitglied</h2>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Status</th>
            <th>Job</th>
        </tr>
    </thead>
    <tbody>

        @*@if (Model.EmployeeTask.EmployeeId != null)
        {
            <tr>
                <td>@Model.EmployeeTask.Employee.ToString()</td>
                <td>@Model.EmployeeTask.Employee.Status</td>
                <td>@Model.EmployeeTask.Employee.Job</td>
                <td>
                    <form asp-action="Delete" asp-route="@Model.EmployeeTask.EmployeeId">
                        <input type="submit" value="Löschen" class="btn btn-danger" />
                    </form>
                </td>
            </tr>
        }
        else
        {
            <tr>
                <td>@Model.EmployeeTask.Employee.ToString()</td>
                <td>@Model.EmployeeTask.Employee.Status</td>
                <td>@Model.EmployeeTask.Employee.Job</td>

            </tr>
        }*@

     
            <tr>
                <td>@Model.EmployeeTask.Employee.Lastname</td>
                <td>@Model.EmployeeTask.Employee.Firstname</td>
                <td>@Model.EmployeeTask.Employee.Status</td>
                <td>@Model.EmployeeTask.Employee.Job</td>
                <td>
                    @*<form asp-action="Delete" asp-route="@Model.EmployeeTask.EmployeeId">
                        <input type="submit" value="Löschen" class="btn btn-danger" />
                    </form>*@
                </td>
            </tr>
 

    </tbody>
    </table>

<h2>Alle Mitarbeiter (ohne Projekt-Mitglieder)</h2>

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Status</th>
            <th>Job</th>
        </tr>
    </thead>
    <tbody>
        @*@foreach (var emp in Model.EmplyoeeNotInTask)*@
        @foreach (var emp in Model.Employees)
        {
        <tr>
            @*// <td>@emp.ToString()</td>*@

            @*<td>@emp.Employee.ToString()</td>
        <td>@emp.Employee.Job</td*@>
            @*<td>@emp.Job</td>*@
            <td>
                @*<form asp-action="Create" asp-controller="EmployeeTasks" asp-route-employeeId="@emp.Id" asp-route-taskId="@Model.EmployeeTask.TaskId">
                    <input type="submit" value="Mitarbeiter hinzufügen" class="btn btn-success" />
                </form>
            </td>*@


            <td>@Model.EmployeeTask.Employee.Lastname</td>
            <td>@Model.EmployeeTask.Employee.Firstname</td>
            <td>@Model.EmployeeTask.Employee.Status</td>
            <td>@Model.EmployeeTask.Employee.Job</td>
        </tr>
        }
    </tbody>
</table>
@*<div>*@