ProjectManager.Web/Controllers/QualificationsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectManager.Core.Contracts;
using ProjectManager.Core.Entities;
using ProjectManager.Web.Models.ViewModel;

namespace ProjectManager.Web.Controllers
{
    public class QualificationsController : Controller
    {
        IUnitOfWork _unitOfWork;

        public QualificationsController(IUnitOfWork unitofwork)
        {
            _unitOfWork = unitofwork;
        }

        /// <summary>
        /// Lukas Schütz Created
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        public IActionResult List()
        {
            QualificationsListViewModel model = new QualificationsListViewModel();
            model.LoadData(_unitOfWork);
            return View(model);
        }

        /// <summary>
        /// Lukas Schütz Created
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult List(QualificationsListViewModel model)
        {
            model.Qualifications = _unitOfWork.Qualifications.GetQualificationByName(model.FilterProjectName);
            return View(model);
        }

        /// <summary>
        /// Lukas Schütz Created
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Lukas Schütz Created
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(Qualification model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _unitOfWork.Qualifications.Add(model);
                    _unitOfWork.Save();
                    return RedirectToAction("List");
                }
                catch (ValidationException validationException)
                {
                    ValidationResult valResult = validationException.ValidationResult;
                    ModelState.AddModelError(nameof(model.QualificationName) + "." + valResult.MemberNames.First(), valResult.ToString());
                    return View(model);
                }
            }

            return View();
        }

        /// <summary>
        /// Lukas Schütz Created
        /// </summary>
        /// <param name="qualId"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int qualId)
        {
            Qualification model = new Qualification();
            model = _unitOfWork.Qualifications.GetById(qualId);

            return View(model);
        }

        /// <summary>
        /// Lukas Schütz Created
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(Qualification model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _unitOfWork.Qualifications.Update(model);
                    _unitOfWork.Save();
                    return RedirectToAction(nameof(List));
                }
                catch (ValidationException validationException)
                {
                    ValidationResult valResult = validationException.ValidationResult;
                    ModelState.AddModelError(nameof(model.QualificationName) + "." + valResult.MemberNames.First(), valResult.ToString());
                    return View(model);
                } 
            }

            return View(model);
        }

        /// <summary>
        /// Lukas Schütz Created
        /// </summary>
        /// <param name="qualId"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int qualId)
        {
            Qualification model = _unitOfWork.Qualifications.GetById(qualId);

            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        /// <summary>
        /// Lukas Schütz Created
        /// </summary>
        /// <param name="qualId"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult DeleteConfirm(int qualId)
        {
            Qualification model = _unitOfWork.Qualifications.GetById(qualId);

            if (model == null)
            {
                return NotFound();
            }

            _unitOfWork.Qualifications.Delete(model);
            _unitOfWork.Save();
            return RedirectToAction(nameof(List));
        }
    }
}

ProjectManager.Web/Views/Qualifications/Create.cshtml
@model ProjectManager.Core.Entities.Qualification

@{
    ViewData["Title"] = "Create";
}

<head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
</head>

<div class="container">
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2>Create</h2>
                </div>
                <div class="panel-body">
                    <form asp-action="Create" asp-controller="Qualifications">

                        <div class="row">
                            <div class="col-md-4"></div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label">Name</label>
                                    <input asp-for="QualificationName" class="form-control" />
                                    <span asp-validation-for="QualificationName" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="pager">
                            <a asp-controller="Qualifications" asp-action="List" class="btn btn-default"><i class="fas fa-chevron-left"></i> Overview</a>
                            <input type="submit" value="Create" class="btn btn-success" />
                        </div>
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

ProjectManager.Web/Views/Qualifications/Delete.cshtml
@model ProjectManager.Core.Entities.Qualification

@{
    ViewData["Title"] = "Delete";
}

<head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
</head>

<div class="container">
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3>Do you want to delete the Qualification "@Model.QualificationName" ?</h3>
                </div>
                <div class="panel-body">
                    <div>
                        <form asp-action="DeleteConfirm" asp-route-qualId="@Model.Id">
                            <div class="pager">
                                <a asp-controller="Qualifications" asp-action="List" class="btn btn-default"><i class="fas fa-chevron-left"></i> Overview</a>
                                <input type="submit" value="Delete" class="btn btn-danger" />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ProjectManager.Web/Views/Qualifications/Edit.cshtml
@model ProjectManager.Core.Entities.Qualification

@{
    ViewData["Title"] = "Edit";
}

<head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
</head>

<div class="container">
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2>Edit</h2>
                </div>
                <div class="panel-body">
                    <form asp-action="Edit">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="row">
                            <div class="col-md-4"></div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label asp-for="QualificationName" class="control-label"></label>
                                    <input asp-for="QualificationName" class="form-control" />
                                    <img src="~/favicon.ico" />
                                    <span asp-validation-for="QualificationName" class="text-danger"></span>
                                </div>
                                <input type="hidden" asp-for="Timestamp" />
                                <input type="hidden" asp-for="Id" />
                                <div class="pager">
                                    <a asp-controller="Qualifications" asp-action="List" class="btn btn-default"><i class="fas fa-chevron-left"></i> Overview</a>
                                    <input type="submit" value="Save" class="btn btn-success" />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

ProjectManager.Web/Views/Qualifications/List.cshtml
@model ProjectManager.Web.Models.ViewModel.QualificationsListViewModel

@{
    ViewData["Title"] = "List";
}


<head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
</head>

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2>Qualifications</h2>
                </div>
                <div class="panel-body">
                    <form asp-controller="Qualifications" asp-action="List">
                        <div class="input-group has-feedback col-md-4">
                            <input asp-for="FilterProjectName" type="text" placeholder="Qualification name" class="form-control" />
                            <span asp-validation-for="FilterProjectName" class="text-danger"></span>
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-primary">
                                    <i class="fas fa-search"></i>
                                </button>
                            </span>
                        </div>
                    </form>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    Name
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Qualifications)
                            {
                                <tr>
                                    @if (item.QualificationName == "Project Manager")
                                    {

                                        <td>
                                            @item.QualificationName
                                        </td>
                                        <td><a><i class="far fa-edit"></i></a></td>
                                        <td><a><i class="far fa-trash-alt"></i></a></td>
                                    }
                                    else
                                    {
                                        <td>
                                            @item.QualificationName
                                        </td>
                                        <td title="Edit"><a asp-controller="Qualifications" asp-action="Edit" asp-route-qualId="@item.Id"><i class="far fa-edit"></i></a></td>
                                        <td title="Delete"><a asp-controller="Qualifications" asp-action="Delete" asp-route-qualId="@item.Id"><i class="far fa-trash-alt"></i></a></td>
                                    }
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>