ProjectManager.Web/Models/ViewModel/Departments/CreateDepartmentViewModel.cs
using ProjectManager.Core.Contracts;
using ProjectManager.Core.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectManager.Web.Models.ViewModel.Departments
{
    public class CreateDepartmentViewModel
    {
        #region properties

        public Department Department { get; set; }

        public bool Success { get; set; }
        public bool Error { get; set; }

        public string RouteString { get; set; }
        public int RouteId { get; set; }

        #endregion

        #region controller-methods

        public void LoadData(string routeString, int routeId)
        {
            RouteString = routeString;
            RouteId = routeId;
        }

        #endregion
    }
}

ProjectManager.Web/Models/ViewModel/Departments/DepartmentsViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjectManager.Core.Contracts;
using ProjectManager.Core.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectManager.Web.Models.ViewModel
{
    public class DepartmentsViewModel
    {
        #region  List

        #region properties - List

        public List<Department> DepartmentList { get; set; }
        public IUnitOfWork UnitOfWork { get; set; }

        #endregion
        #region controller-methods - List

        public void LoadListData(IUnitOfWork uow)
        {
            this.DepartmentList = uow.Departments.GetAll();
            UnitOfWork = uow;
        }

        #endregion
        #region model-methods List

        public int CountEmployeesOfThisDepartment(Department department, IUnitOfWork uow)
        {
            return uow.Employees.GetEmployeeByDepartmentId(department.Id).Count;
        }

        #endregion

        #endregion

        #region Details

        #region properties

        public List<Employee> EmployeeList { get; set; }
        public Department Department { get; set; }

        #endregion
        #region controller-methods - Details

        public void LoadDeatilsData(int departmentId, IUnitOfWork uow)
        {
            EmployeeList = uow.Employees.GetEmployeeByDepartmentId(departmentId);
            Department = uow.Departments.GetById(departmentId);
        }

        #endregion

        #endregion

        #region Delete

        #region properties

        public Department AssignDepartment { get; set; }
        public SelectList DepartmentSelectList { get; set; }
        public string Assign { get; set; }
        public string Change { get; set; }
        public string ChoosenDepartment { get; set; }

        #endregion
        #region controller-methods
        //EmployeeList ist in der region Details\Properties zu finden
        //Department ist in der region Details\Properties zu finden
        public void LoadConfirmDeleteData(int departmentId, IUnitOfWork uow)
        {
            Department = uow.Departments.GetById(departmentId);
            EmployeeList = uow.Employees.GetEmployeeByDepartmentId(Department.Id);

            this.DepartmentList = uow.Departments.GetAllWithoutThisDepartmentId(departmentId);
            this.DepartmentSelectList = new SelectList(this.DepartmentList, nameof(Department.Id), nameof(Department.DeptName));
        }

        #endregion

        #endregion
    }
}

ProjectManager.Web/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectManager.Core.Contracts;
using ProjectManager.Core.Entities;
using ProjectManager.Web.Models.ViewModel;
using ProjectManager.Web.Models.ViewModel.Departments;

namespace ProjectManager.Web.Controllers
{
    public class DepartmentsController : Controller
    {
        #region unitOfWork

        IUnitOfWork _unitOfWork;

        public DepartmentsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        #endregion

        #region List, Details

        public IActionResult List()
        {
            DepartmentsViewModel model = new DepartmentsViewModel();
            model.LoadListData(_unitOfWork);
            return View(model);
        }

        public IActionResult Details(int departmentId)
        {
            DepartmentsViewModel model = new DepartmentsViewModel();
            model.LoadDeatilsData(departmentId, _unitOfWork);
            return View(model);
        }

        #endregion

        #region Delete, ConfirmDelete

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int departmentId)
        {
            DepartmentsViewModel model = new DepartmentsViewModel();

            if (model.CountEmployeesOfThisDepartment(_unitOfWork.Departments.GetById(departmentId), _unitOfWork) == 0)
            {
                DeleteDepartment(_unitOfWork.Departments.GetById(departmentId));
                return RedirectToAction(nameof(List));
            }
            else
            {
                return RedirectToAction(nameof(ConfirmDelete), new { departmentId = departmentId });
            }
        }

        [Authorize(Roles = "Admin")]
        public IActionResult ConfirmDelete(int departmentId)
        {
            DepartmentsViewModel model = new DepartmentsViewModel();
            model.LoadConfirmDeleteData(departmentId, _unitOfWork);
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult ConfirmDelete(DepartmentsViewModel model)
        {
            model.AssignDepartment = _unitOfWork.Departments.GetById(model.AssignDepartment.Id);
            model.EmployeeList = _unitOfWork.Employees.GetEmployeeByDepartmentId(model.Department.Id);

            foreach (var emp in model.EmployeeList)
            {
                emp.DepartmentId = model.AssignDepartment.Id;
                emp.Department = model.AssignDepartment;

                _unitOfWork.Employees.Update(emp);
                _unitOfWork.Save();
            }

            DeleteDepartment(_unitOfWork.Departments.GetById(model.Department.Id));

            return RedirectToAction(nameof(List));
        }

        #region Delete, ConfirmDelete - Methods

        private void DeleteDepartment(Department department)
        {
            try
            {
                _unitOfWork.Departments.Delete(department);
                _unitOfWork.Save();
            }
            catch (Exception ex)
            {

            }
        }

        #endregion

        #endregion

        #region Create

        [Authorize(Roles = "Admin")]
        public IActionResult Create(string routeString, int routeId)
        {
            CreateDepartmentViewModel model = new CreateDepartmentViewModel();
            model.LoadData(routeString, routeId);
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Create(CreateDepartmentViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _unitOfWork.Departments.Add(model.Department);
                    _unitOfWork.Departments.Add(model.Department);
                    _unitOfWork.Save();
                    model.Success = true;
                }
                catch (ValidationException ex)
                {
                    model.Error = true;
                }
            }

            return View(model);
        }

        #endregion


    }
}

ProjectManager.Web/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProjectManager.Core.Contracts;
using ProjectManager.Core.Entities;
using ProjectManager.Web.Models;
using ProjectManager.Web.Models.ViewModel;
using ProjectManager.Web.Models.ViewModel.Employees;
using Task = ProjectManager.Core.Entities.Task;

namespace ProjectManager.Web.Controllers
{
    public class EmployeesController : Controller
    {
        #region fields

        IUnitOfWork _unitOfWork;
        private UserManager<ApplicationUser> _userManager;
        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        #endregion

        #region Constructor

        public EmployeesController(IUnitOfWork unitOfWork, UserManager<ApplicationUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
        }

        #endregion

        #region List

        public IActionResult List()
        {
            EmployeesListViewModel model = new EmployeesListViewModel();
            model.LoadData(_unitOfWork);

            return View(model);
        }

        [HttpPost]
        public IActionResult List(EmployeesListViewModel model)
        {
            if (model.LastnameFilter != null)
            {
                model.LoadListData(_unitOfWork, 1);
            }
            else if (model.FirstnameFilter != null)
            {
                model.LoadListData(_unitOfWork, 2);
            }
            else if (model.JobFilter != null)
            {
                model.LoadListData(_unitOfWork, 3);
            }
            else if (model.DepartmentFilter != null)
            {
                model.LoadListData(_unitOfWork, 4);
            }
            else
            {
                return NotFound();
            }

            return View(model);
        }

        #endregion

        #region Profil

        public async Task<ActionResult> Profil(int employeeId)
        {
            EmployeesProfilViewModel model = new EmployeesProfilViewModel();

            var user = await GetCurrentUserAsync();

            var UserId = (int)user?.EmployeeId;

            if (employeeId == 0)
            {
                model.IsUserMe = true;
                model.LoadProfilData(_unitOfWork, UserId);
            }
            else
            {
                model.IsUserMe = CheckIfUserIsMe(UserId, employeeId);
                model.LoadProfilData(_unitOfWork, employeeId);
            }

            if (model.Employee == null)
                return NotFound();

            return View(model);
        }

        public IActionResult EditProfil(int employeeId)
        {
            EmployeesEditProfilViewModel model = new EmployeesEditProfilViewModel();
            model.LoadEditProfilData(_unitOfWork, employeeId);
            if (model.Employee == null)
                return NotFound();

            return View(model);
        }

        [HttpPost]
        public IActionResult EditProfil(EmployeesEditProfilViewModel model)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Employees.Update(model.Employee);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Profil), new
                {
                    employeeId = model.Employee.Id
                });
            }
            else
            {
                model.Error = true;
                model.LoadEditProfilData(_unitOfWork, model.Employee.Id);
                return View(model);
            }
        }
        #endregion

        #region Dashboard
        public async Task<ActionResult> Feed(int employeeId, string buttonClicked, bool priority, string error)
        {
            EmployeesFeedViewModel model = new EmployeesFeedViewModel();
            var user = await GetCurrentUserAsync();

            var UserId = (int)user?.EmployeeId;

            if (employeeId == 0)
            {
                model.IsUserMe = true;
                model.LoadDashboardData(UserId, _unitOfWork);
            }
            else if (buttonClicked == null)
            {
                model.IsUserMe = CheckIfUserIsMe(UserId, employeeId);
                model.LoadDashboardData(employeeId, _unitOfWork);
            }
            else
            {
                model.IsUserMe = CheckIfUserIsMe(UserId, employeeId);
                model.Employee = _unitOfWork.Employees.GetById(employeeId);
                model.ButtonClicked = buttonClicked;
                GetFilteredList(model, priority);
            }

            if (error != null)
                HandleOccuredError(model, error);

            if (model == null)
                return NotFound();

            return View(model);
        }

        [HttpPost]
        public IActionResult Feed(EmployeesFeedViewModel model)
        {
            if (model.ProjectFilter != null)
            {
                model.LoadProjectDashboardData(model.Employee.Id, _unitOfWork, "All", IsPriorityButtonClicked(model.PriorityFilter));
            }
            else if (model.Assigned != null)
            {
                model.LoadDashboardData(model.Employee.Id, _unitOfWork);
            }
            else if (model.GeneralFilter != null)
            {
                model.LoadProjectDashboardData(model.Employee.Id, _unitOfWork, "General", IsPriorityButtonClicked(model.PriorityFilter));
            }
            else if (model.PriorityFilter != null)
            {
                GetFilteredList(model, IsPriorityButtonClicked(model.PriorityFilter));
            }
            else if (model.Search != null)
            {
                GetFilteredList(model, IsPriorityButtonClicked(model.PriorityFilter));
            }
            else
            {
                return NotFound();
            }

            return View(model);
        }

        public IActionResult DeleteAppointment(int employeeId, int appointmentId, string buttonClicked, string priorityButton)
        {
            DashboardDisplay dashboardDisplay = _unitOfWork.DashboardDisplays.GetByEmployeeIdAndAppointmentId(employeeId, appointmentId);

            this.DeleteDashBoardTask(dashboardDisplay);
            _unitOfWork.Save();

            return RedirectToAction(nameof(Feed), new
            {
                employeeId = employeeId,
                buttonClicked = buttonClicked,
                priority = IsPriorityButtonClicked(priorityButton)
            });
        }

        public IActionResult AddTask(int employeeId, int taskId, string buttonClicked, string priorityButton)
        {
            return RedirectToAction(nameof(Feed), new
            {
                employeeId = employeeId,
                buttonClicked = buttonClicked,
                priority = IsPriorityButtonClicked(priorityButton),
                error = CheckIfEmployeeTaskExists(employeeId, taskId)
            });
        }

        #region Feed : Methods

        public void GetFilteredList(EmployeesFeedViewModel model, bool priority)
        {
            if (model.ButtonClicked == "Project")
            {
                model.LoadProjectDashboardData(model.Employee.Id, _unitOfWork, "All", priority);
            }
            else if (model.ButtonClicked == "Assigned")
            {
                model.LoadDashboardData(model.Employee.Id, _unitOfWork);
            }
            else if (model.ButtonClicked == "General")
            {
                model.LoadProjectDashboardData(model.Employee.Id, _unitOfWork, "General", priority);
            }
        }

        public string CheckIfEmployeeTaskExists(int employeeId, int taskId)
        {
            string errorMessage = null;
            EmployeeTask employeeTask = new EmployeeTask();
            employeeTask = _unitOfWork.EmployeeTasks.GetByEmployeeIdAndTaskId(employeeId, taskId);

            if (employeeTask == null)
            {
                employeeTask = GenerateEmployeetask(employeeId, taskId);

                if (CreateEmployeeTask(employeeTask))
                {
                    if (!SetUpForDashboardDisplay(employeeTask))
                    {
                        errorMessage = "Error during the creation of the DashboardDisplay!";
                    }
                }
                else
                {
                    errorMessage = "Error during the creation of the EmployeeTask!";
                }
            }
            else
            {
                employeeTask.Picked = true;

                if (UpdateEmployeeTask(employeeTask))
                {
                    if (!SetUpForDashboardDisplay(employeeTask))
                    {
                        errorMessage = "Error during the creation of the DashboardDisplay!";
                    }
                }
                else
                {
                    errorMessage = "Error during the update of the EmployeeTask!";
                }
            }

            return errorMessage;
        }

        private bool IsPriorityButtonClicked(string priority)
        {
            return priority != null;
        }

        private void HandleOccuredError(EmployeesFeedViewModel model, string error)
        {
            model.Error = true;
            model.Errormessage = error;
        }
        #endregion

        #endregion

        #region FinishOrPass

        public IActionResult FinishOrPass(int employeeId, int taskId, string buttonClicked, bool priority)
        {
            EmployeesFinishOrPassViewModel model = new EmployeesFinishOrPassViewModel();
            model.LoadData(_unitOfWork, employeeId, taskId);
            model.ButtonClicked = buttonClicked;
            model.Priority = priority;
            return View(model);
        }

        [HttpPost]

ProjectManager.Web/Views/Departments/ConfirmDelete.cshtml
@model ProjectManager.Web.Models.ViewModel.DepartmentsViewModel

<!doctype html>

<html lang="de">
<head>
    <title></title>
    <meta charset="utf-8" />

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-theme.css" rel="stylesheet" />
</head>
<body>
    <form asp-controller="Departments" asp-action="ConfirmDelete">
        <div class="container" style="width:700px">
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h2>Confirm the delete of @Model.Department.DeptName</h2>
                        </div>
                        <div class="panel-heading">
                            <label class="control-label">Choose a new department for your employees</label>
                        </div>

                        <div class="panel-body">
                            <div class="form-inline">
                                <select asp-for="AssignDepartment.Id" asp-items="@Model.DepartmentSelectList" class="form-control" style="width:159px"></select>
                                <input asp-for="Assign" type="submit" value="Assign" class="btn btn-primary" />
                                <span asp-validation-for="Assign" class="text-danger" />
                            </div>

                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Lastname</th>
                                        <th>Firstname</th>
                                        <th>Job</th>
                                    </tr>
                                </thead>
                                @foreach (var employee in Model.EmployeeList)
                                {
                                    <tr>
                                        <td>@employee.Lastname</td>
                                        <td>@employee.Firstname</td>
                                        <td>@employee.Job</td>
                                    </tr>
                                }
                            </table>
                            <div class="form-group">

                                <a title="Click here to crate a new department" style="width:200px" class="btn btn-primary" asp-controller="Departments" asp-action="Create" asp-route-routeString="ConfirmDelete"
                                   asp-route-routeId="@Model.Department.Id">Create department</a>

                                <a title="Click here to go back to the departmentlist" style="width:200px" class="btn btn-primary" asp-controller="Departments" asp-action="List">Back</a>
                            </div>
                        </div>

                        <input asp-for="Department.Id" value="@Model.Department.Id" type="hidden" />
                        <input asp-for="Department.DeptName" value="@Model.Department.DeptName" type="hidden" />
                    </div>
                </div>
            </div>
        </div>
    </form>
</body>
</html>

ProjectManager.Web/Views/Departments/Create.cshtml
@model ProjectManager.Web.Models.ViewModel.Departments.CreateDepartmentViewModel
@{
    ViewData["Title"] = "Create";
}

<!doctype html>

<html lang="de">
<head>
    <title></title>
    <meta charset="utf-8" />

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-theme.css" rel="stylesheet" />
</head>
<body>
    <div class="container" style="width:500px">
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h2>Create department</h2>
                    </div>
                    @if (Model.Success == true)
                    {
                        <div class="panel-success">
                            <div class="panel-heading">
                                <h4>Saveing was successful!</h4>
                            </div>
                        </div>
                    }

                    @if (Model.Error == true)
                    {
                        <div class="panel-danger">
                            <div class="panel-heading">
                                <h4>The choosen name is already existing!</h4>
                            </div>
                        </div>
                    }
                    <div class="panel-body">
                        <div class="row">

                            <form asp-controller="Departments" asp-action="Create">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="form-group">
                                    <label asp-for="Department.DeptName" class="control-label"></label>
                                    <input required="true" asp-for="Department.DeptName" class="form-control" />
                                    <span asp-validation-for="Department.DeptName" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Department.DeptLocation" class="control-label"></label>
                                    <input required="true" asp-for="Department.DeptLocation" class="form-control" />
                                    <span asp-validation-for="Department.DeptLocation" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Create Department" class="btn btn-primary" style="width:232px" />

                                    <a asp-controller="Departments" asp-action="@Model.RouteString" asp-route-departmentId="@Model.RouteId" class="btn btn-success" style="width:232px">Back</a>
                                </div>
                                <input type="hidden" value="@Model.RouteString" asp-for="RouteString" />
                                <input type="hidden" value="@Model.RouteId" asp-for="RouteId" />
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>   
</body>
</html>

ProjectManager.Web/Views/Departments/Details.cshtml
@model ProjectManager.Web.Models.ViewModel.DepartmentsViewModel
@{
    ViewData["Title"] = "Details";
}

<!doctype html>

<html lang="de">
<head>
    <title></title>
    <meta charset="utf-8" />

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-theme.css" rel="stylesheet" />
</head>
<body>
    <form asp-controller="Departments" asp-action="Details" class="form-inline">
        <div class="container" style="width:875px">
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h2>@Model.Department.DeptName</h2>
                        </div>
                        <div class="panel-body">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>Lastname</th>
                                        <th>Firstname</th>
                                        <th>Job</th>
                                    </tr>
                                </thead>
                                @foreach (var employee in Model.EmployeeList)
                                {
                                    <tr title="Click here to see the dashboard of this employee!" onclick="location.href = '@(Url.Action("Feed", "Employees", new { employeeId = employee.Id}))'">
                                        <td class="icon-bar" title="Click here to see the profil of this person"><a class="active" asp-controller="Employees" asp-action="Profil" asp-route-employeeId="@employee.Id"><i class="fa fa-user" aria-hidden="true"></i></a></td>
                                        <td>@employee.Lastname</td>
                                        <td>@employee.Firstname</td>
                                        <td>@employee.Job</td>
                                    </tr>
                                }
                            </table>

                            <div class="form-group">
                                <a asp-controller="Departments" asp-action="List" class="btn btn-primary" style="width:200px">Back</a>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </form>
</body>
</html>

ProjectManager.Web/Views/Departments/List.cshtml
@model ProjectManager.Web.Models.ViewModel.DepartmentsViewModel

@{
    ViewData["Title"] = "List";
}

<!doctype html>

<html lang="de">
<head>
    <title></title>
    <meta charset="utf-8" />

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-theme.css" rel="stylesheet" />
</head>
<body>
    <div class="container" style="width:700px">
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h2>Departments</h2>
                    </div>
                    <div class="panel-body">
                        <div class="form-group">
                            <a asp-controller="Departments" asp-action="Create" asp-route-routeString="List" class="btn btn-primary">Create Department</a>
                        </div>

                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Departmentname</th>
                                    <th>Departmentlocation</th>
                                    <th>Amount of employees</th>
                                    <th></th>
                                </tr>
                            </thead>

                            @foreach (var department in Model.DepartmentList)
                            {
                            <tr title="Click here to see the employees of this department" onclick="location.href = '@(Url.Action("Details", "Departments", new { departmentId = department.Id}))'">
                                <td>@department.DeptName</td>
                                <td>@department.DeptLocation</td> 
                                <td>@Model.CountEmployeesOfThisDepartment(department, Model.UnitOfWork)</td>
                                <td><a title="Click here to delete this department!"  asp-controller="Departments" asp-action="Delete" asp-route-departmentId="@department.Id"><i class="fa fa-trash-alt" aria-hidden="true"></i></a></td>
                            </tr>
                            }
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>